FROM nginx

MAINTAINER Brent Salisbury <brent.salisbury@gmail.com>

# Replace the default index.html with some funs ascii art.
# run and listen on port 8080 with the following for:
# docker run -it --rm  -p 8080:80 networkstatic/nginx_kittah
ADD index.html /usr/share/nginx/html/index.html
